### PR TITLE
feat(new_faucet): added https://get-shm.online

### PR DESCRIPTION
**Pull request by berejznoy**

### CODE REVIEW

**Review by MarcusWentz — CHANGES_REQUESTED** [review]
1. The faucet is empty when I tried it. Please refill it.

2. Do you have a captcha to prevent faucet request spam? 
If not, please add this so I can test this.

4. Do you have an open source repo to the faucet backend?
If not, please create this so I can see this.

**Comment by berejznoy** [comment]
1)The faucet is not empty. Network problems. Look in explorer - https://explorer-sphinx.shardeum.org/account/0xc024ef4e604aeaf94baea5daa8c9decf530b1652

2) There is a hidden captcha
image
In addition to captcha, there is also fraud protection associated with storing keys in Redis.

3) Yes. Sure - https://github.com/berejznoy/shardeum-faucet

**Comment by MarcusWentz** [comment]
1. I will try again once Validator Version 1.1.3 is out.

2. I have not seen this hidden captcha before. Do you have a demo link where it activates when it detects spam?

3. Please create a new repo for this, since the original repo it is forked from is subject to change.

**Comment by MarcusWentz** [comment]
Please also display 
the faucet SHM balance and the faucet address to verify on the Shardeum Betanet 1.X Explorer.

**Comment by berejznoy** [comment]
1. I'm looking forward to
2. Sorry I mean invisible reCaptcha. Read more [here](https://developers.google.com/recaptcha/docs/invisible?hl=en) .
Try several times to refresh the page and request tokens
image
3. Done
4. 0xC024EF4e604AEAf94baea5dAa8C9decf530b1652
image

**Comment by MarcusWentz** [comment]
Please add the faucet address and faucet SHM balance to the faucet frontend (it doesn't appear yet).

**Comment by MarcusWentz** [comment]
Link to the new backend repo?

**Comment by berejznoy** [comment]
Hello @MarcusWentz 
Balance and link to explorer added 
The recreated repository is available at - https://github.com/berejznoy/shardeum-faucet

**Comment by MarcusWentz** [comment]
Please combine all commits into 1 commit.

**Comment by berejznoy** [comment]
@MarcusWentz Hello. Done

**Pull request merged**
