### PR TITLE
Fix wrong link for docs

### PR DESCRIPTION
**Pull request by xiaolou86**

### CODE REVIEW

**Comment by MarcusWentz** [comment]
Closing since the original links work and are shorter.

**Comment by xiaolou86** [comment]
Hi @MarcusWentz, the original links is 404.

**Comment by MarcusWentz** [comment]
Where do you see 404 links? I am clicking on every link on Quickstart with no error.
Please specify how you get to the 404 links with the current docs so I can test this as well.

**Comment by xiaolou86** [comment]
Sorry sir, it's my fault. I just find the link in the github is 404, but it works well on our website.

**Comment by xiaolou86** [comment]
I need to learn more about Docusaurus

**Comment by MarcusWentz** [comment]
No worries. If there are other issues or errors that appear in the docs,
please open an issue or a PR and I can test the issue as well. Thank you.

**Pull request closed without merging**
